In [1]:
import sys
import os
import sqlite3
import pandas as pd

db_file = "database.db"

sys.path.append(os.path.abspath("routes"))

from munro_data import *

In [2]:
conn = sqlite3.connect(db_file)
cur = conn.cursor()

In [3]:
#munro_df = pd.read_sql_query("SELECT * FROM munros", conn)
#munro_df.head()

In [9]:
user_df = pd.read_sql_query("SELECT * FROM bags where user_id = 'u001'", conn)
user_df

,user_id,munro_id,date,distance,friends,notes
0,u001,m056,9/7/2019,None,Scott,Set out to do 4 but weather was awful. Long wa...
1,u001,m181,20/07/2019,13.05km,"Lou, mum, dad",Louise's 21st birthday! Good weather
2,u001,m254,6/8/2020,16.37km,Scott,Pandaaaas. Did the Cobbler as well.
3,u001,m116,6/8/2020,16.37km,Scott,Pandaaaas. Did the Cobbler as well.
4,u001,m246,16/09/2020,10.82km,Scott,Set off at 1pm - probably a mistake. Had to wa...
5,u001,m145,2/10/2020,15.78km,Scott,Bluebird day in October - took a Friday off
6,u001,m230,2/10/2020,15.78km,Scott,Bluebird day in October - took a Friday off
7,u001,m086,10/10/2020,16.84km,"Scott, Lou",Bit chilly. Had to go back over the first one ...
8,u001,m220,10/10/2020,16.84km,"Scott, Lou",Bit chilly. Had to go back over the first one ...
9,u001,m015,31/05/2021,11.77km,"Scott, Lou",May bank holiday - another bluebird day. Quite...
10,u001,m017,31/05/2021,11.77km,"Scott, Lou",May bank holiday - another bluebird day. Quite...
11,u001,m112,6/7/2021,13.49km,"Amy F, Jack, Hazel","Glenshee holiday munros, Team Walk. Started at..."
12,u001,m070,6/7/2021,13.49km,"Amy F, Jack, Hazel","Glenshee holiday munros, Team Walk. Started at..."
13,u001,m068,6/7/2021,13.49km,"Amy F, Jack, Hazel","Glenshee holiday munros, Team Walk. Started at..."
14,u001,m228,19/07/2021,14.09km,Lou,For Louise's birthday - too hot! Missed the su...
15,u001,m134,5/6/2022,17.61km,"Scott, Amy F, Jack, Ben, James B, Olivia, Hazel",Back from America into three meaty munros. Exc...
16,u001,m031,5/6/2022,17.61km,"Scott, Amy F, Jack, Ben, James B, Olivia, Hazel",Back from America into three meaty munros. Exc...
17,u001,m034,5/6/2022,17.61km,"Scott, Amy F, Jack, Ben, James B, Olivia, Hazel",Back from America into three meaty munros. Exc...
18,u001,m163,16/07/2022,15.44km,"Scott, Darah",With Darah - think she was still friends with ...
19,u001,m183,16/07/2022,15.44km,"Scott, Darah",With Darah - think she was still friends with ...
20,u001,m033,23/07/2022,14.89km,"Scott, Hazel, Matty, Amy F, Jack, Ben, Eliza",Invergarry holiday munros - hit a bird with th...
21,u001,m048,23/07/2022,14.89km,"Scott, Hazel, Matty, Amy F, Jack, Ben, Eliza",Invergarry holiday munros - hit a bird with th...
22,u001,m069,19/09/2022,10.29km,"Scott, Hazel, James B",Statty funes - another one that starts high up...
23,u001,m261,19/09/2022,10.29km,"Scott, Hazel, James B",Statty funes - another one that starts high up...
24,u001,m005,29/07/2023,17.63km,"Scott, Amy F, Jack, Eliza, Hazel, Ben, James B...",Grantown holiday munros - big stomp but high s...
25,u001,m001,29/07/2023,17.63km,"Scott, Amy F, Jack, Eliza, Hazel, Ben, James B...",Grantown holiday munros - big stomp but high s...
26,u001,m019,12/7/2024,19.81km,"Scott, Amy F, Jack, Hazel, James B, Olivia, Ben",Braemar holiday munro - all the walks were lon...
27,u001,m280,14/07/2024,9.78km,"Scott, Matty",From Glenshee ski centre on the way home from ...
28,u001,m178,14/07/2024,9.78km,"Scott, Matty",From Glenshee ski centre on the way home from ...
29,u001,m243,14/07/2024,9.78km,"Scott, Matty",From Glenshee ski centre on the way home from ...
30,u001,m279,27/07/2024,12.25km,Lou,Always choose hot days to do these... swim at ...
31,u001,m101,26/07/2025,19.85km,"Scott, Amy F, Jack, Eliza, Matty, Hazel, James...",Loch Tay holiday munros - pleasant first half ...
32,u001,m186,26/07/2025,19.85km,"Scott, Amy F, Jack, Eliza, Matty, Hazel, James...",Loch Tay holiday munros - pleasant first half ...
33,u001,m090,26/07/2025,19.85km,"Scott, Amy F, Jack, Eliza, Matty, Hazel, James...",Loch Tay holiday munros - pleasant first half ...
34,u001,m167,26/07/2025,19.85km,"Scott, Amy F, Jack, Eliza, Matty, Hazel, James...",Loch Tay holiday munros - pleasant first half ...
35,u001,m256,2025-08-30,None,scott,sunny

In [15]:
cursor.execute("PRAGMA table_info('users');")
columns = cursor.fetchall()

In [16]:
columns

[(0, 'user_id', 'TEXT', 0, None, 0),
 (1, 'user_name', 'TEXT', 0, None, 0),
 (2, 'password', 'INTEGER', 0, None, 0)]

In [8]:
conn.close()

In [20]:
bags_df = pd.read_sql_query("SELECT * FROM bags", conn)
bags_df

,user_id,munro_id,date,distance,friends,notes
0,u001,m056,9/7/2019,None,Scott,Set out to do 4 but weather was awful. Long wa...
1,u001,m181,20/07/2019,13.05km,"Lou, mum, dad",Louise's 21st birthday! Good weather
2,u001,m254,6/8/2020,16.37km,Scott,Pandaaaas. Did the Cobbler as well.
3,u001,m116,6/8/2020,16.37km,Scott,Pandaaaas. Did the Cobbler as well.
4,u001,m246,16/09/2020,10.82km,Scott,Set off at 1pm - probably a mistake. Had to wa...
...,...,...,...,...,...,...
84,u000,m280,2024-07-14,None,None,None
85,m005,m220,0008-08-08,None,None,None
86,m009,m040,0088-08-08,None,None,None
87,m009,m169,0099-09-09,None,None,None
88,m009,m276,0088-08-08,None,None,None

In [6]:
#data.drop(columns="munro_id")

In [17]:
cursor.execute("""
    SELECT latitude, longitude
    FROM munros
    WHERE munro_id = 'm226'
""")

coords = cursor.fetchone()

In [18]:
coords

(57.204869, -6.211385)